### ISSUE TITLE
Supported Features

### ISSUE THREAD

**Issue by lcharbon** [honzahommer/grok-js#15]
I am trying to implement [this](https://github.com/vjeantet/grok/blob/master/patterns/mongodb) grok pattern. It includes custom regex and patterns referencing other patterns. Is this possible in grok-js? The file seems to load fine but all I seem to be getting as a return is `null`.

**Comment by honzahommer** [comment]
@lcharbon Yes, it is possible.
https://github.com/honzahommer/grok-js/blob/00c6115c847bd14da0dedf43edeb2ed53a05f8fe/lib/patterns/mongodb#L1-L4
