### ISSUE TITLE
Conflict With KafkaJs

### ISSUE THREAD

**Issue by lcharbon** [honzahommer/grok-js#19]
Importing `grok-js` to an app with [kafkajs](https://github.com/tulios/kafkajs) will break  [kafkajs](https://github.com/tulios/kafkajs).  `await producer.send()` will fail and return an empty array.

See minimal example [here](https://github.com/lcharbon/gork-conflict).

In this example, if const grok = require('grok-js'); is uncommented kafkajs will stop working.

Issue submitted to `kafkajs` [here](https://github.com/tulios/kafkajs/issues/623).

**Comment by Nevon** [comment]
I debugged this a little bit and found that it's because `grok-js` depends on the `collections` library, which replaces `Array.from` with an implementation that doesn't work with iterables. I would recommend dropping `collections` as a dependency.

**Comment by honzahommer** [comment]
https://www.npmjs.com/package/grok-js/v/3.3.0

**Comment by honzahommer** [comment]
https://github.com/montagejs/collections/pull/212
